export const englishWordsWithMeanings = [
  { vocabulary: 'apple', meaning: 'quả táo' },
  { vocabulary: 'banana', meaning: 'quả chuối' },
  { vocabulary: 'computer', meaning: 'máy tính' },
  { vocabulary: 'dog', meaning: 'con chó' },
  { vocabulary: 'elephant', meaning: 'con voi' },
  { vocabulary: 'flower', meaning: 'hoa' },
  { vocabulary: 'guitar', meaning: 'đàn guitar' },
  { vocabulary: 'house', meaning: 'nhà' },
  { vocabulary: 'internet', meaning: 'internet' },
  { vocabulary: 'jacket', meaning: 'áo khoác' },
  { vocabulary: 'kiwi', meaning: 'quả kiwi' },
  { vocabulary: 'lion', meaning: 'con sư tử' },
  { vocabulary: 'moon', meaning: 'mặt trăng' },
  { vocabulary: 'notebook', meaning: 'sổ tay' },
  { vocabulary: 'ocean', meaning: 'đại dương' },
  { vocabulary: 'piano', meaning: 'đàn piano' },
  { vocabulary: 'queen', meaning: 'nữ hoàng' },
  { vocabulary: 'rabbit', meaning: 'con thỏ' },
  { vocabulary: 'sun', meaning: 'mặt trời' },
  { vocabulary: 'tree', meaning: 'cây' },
  { vocabulary: 'umbrella', meaning: 'ô' },
  { vocabulary: 'violin', meaning: 'đàn violin' },
  { vocabulary: 'water', meaning: 'nước' },
  { vocabulary: 'xylophone', meaning: 'đàn xylophone' },
  { vocabulary: 'yacht', meaning: 'du thuyền' },
  { vocabulary: 'zebra', meaning: 'ngựa vằn' },
  { vocabulary: 'airplane', meaning: 'máy bay' },
  { vocabulary: 'book', meaning: 'sách' },
  { vocabulary: 'car', meaning: 'xe hơi' },
  { vocabulary: 'desk', meaning: 'bàn làm việc' },
];
